config/routes.rb
Dashboard::Application.routes.draw do
  resources :notifications

  resources :samples

  resources :probes

  resources :thresholds

  resources :widgets do
    member do 
      get   'process_samples'
    end
    collection do
      post  'sort'
      get   'record_all_samples'
    end
  end

  root :to => 'probes#index'

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  
  belongs_to :widget
  after_save :check_for_notifications
  serialize :details, Hash
  
  CHECK_RETRY_BEFORE_NOTIFICATION   = Settings.retries_before_notification || 3
  
  SAMPLE_STATUS_OK                  = 0
  SAMPLE_STATUS_ALERT               = 1
  SAMPLE_STATUS_WARNING             = 2
  SAMPLE_STATUS_UNRESPONSIVE        = 3
  
  NOTIFICATION_STATUS_PROBLEM       = 10
  NOTIFICATION_STATUS_RECOVERY      = 11
  NOTIFICATION_STATUS_UNRESPONSIVE  = 12
    
  def check_for_notifications
  	# send alert notification if status has changed to'alert' since 3 samples
  	# don't send notification if already sent
    if widget.has_same_status_several_times?(SAMPLE_STATUS_ALERT, CHECK_RETRY_BEFORE_NOTIFICATION)
      if !widget.notifications.last or widget.notifications.last.status != NOTIFICATION_STATUS_PROBLEM
        notification = Notification.new ({
          :widget_id  => widget.id,
          :date       => DateTime.now,
          :status     => NOTIFICATION_STATUS_PROBLEM
        })
        notification.save!
        NotificationMailer.notification(notification).deliver
        logger.debug 'problem notification'
      end
    end

  	# send unresponsive notification if status has changed to 'ok' since 3 samples
  	# don't send notification if already sent
    #TODO : IF WAS ALERT ONLY
    if widget.has_same_status_several_times?(SAMPLE_STATUS_UNRESPONSIVE, CHECK_RETRY_BEFORE_NOTIFICATION)
      logger.debug 'unresponsive status for at least 3 times'
      if !widget.notifications.last or widget.notifications.last.status != NOTIFICATION_STATUS_UNRESPONSIVE
        notification = Notification.new ({
          :widget_id  => widget.id,
          :date       => DateTime.now,
          :status     => NOTIFICATION_STATUS_UNRESPONSIVE
        })
        notification.save!
        NotificationMailer.notification(notification).deliver
        logger.debug 'unresponsive notification'
      end
    end   
    
  	# send recovery notification if status has changed to 'ok' since 3 samples
  	# send notification only if was PROBLEM or UNRESPONSIVE
    if widget.has_same_status_several_times?(SAMPLE_STATUS_OK, CHECK_RETRY_BEFORE_NOTIFICATION)
      logger.debug 'ok status for at least 3 times'
      if widget.notifications.last and (widget.notifications.last.status == NOTIFICATION_STATUS_UNRESPONSIVE or  widget.notifications.last.status == NOTIFICATION_STATUS_PROBLEM)
        notification = Notification.new ({
          :widget_id  => widget.id,
          :date       => DateTime.now,
          :status     => NOTIFICATION_STATUS_RECOVERY
        })
        notification.save!
        NotificationMailer.notification(notification).deliver
        logger.debug 'recovery notification'
      end
    end    
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.json
  def index
    @number_of_days = params[:days].to_i
    @number_of_days = 1 if @number_of_days == 0
    @probes = ::Probe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
end

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :widget_id %><br />
    <%= f.number_field :widget_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/_report.html.erb
<ul class="report">
	<% for probe in probes %>
	<li class="probe-section">
		<h3><%= probe.title %><span style="float:right"><%= (Time.now - 3600 * 24 * days).strftime("%Y-%m-%d %H:%M") %> - <%= Time.now.strftime("%Y-%m-%d %H:%M") %></h3>
		<ul>
			<% for widget in probe.widgets.order('position ASC') %>
			<li class="widget-section">
				<h4><%= widget.title %></h4>
				<% data = widget.process_samples(days) %>
				<h5><%= data['average'] %><%= widget.unit %></h5>
				<img src="http://chart.googleapis.com/chart?chxr=0,<%= widget.min %>,<%= widget.max %>&chxs=0,00000042,11.5,0,lt,0000006A&chxt=y&chs=360x53&cht=lc&chco=000000&chd=<%= data['encoded_graph'] %>&chg=14.3,-1,2,2&chls=2,4,0&chm=B,0000000D,0,0,0" width="360" height="53" alt="" />
			</li>
			<% end %>
		</ul>
	</li>
	<% end %>
</ul>

app/views/samples/_report_ajax.html.erb
<ul class="report probes probes-report" data-days="<%= days %>">
	<% for probe in probes %>
	<li class="probe-section">
		<h3><%= probe.title %><span style="float:right"><%= (Time.now - 3600 * 24 * days).strftime("%Y-%m-%d %H:%M") %> - <%= Time.now.strftime("%Y-%m-%d %H:%M") %></h3>
		<ul id="probe-<%= probe.id %>-widgets">

		</ul>
	</li>
	<hr style="clear:both; padding-bottom:0px; border:none;"/>
	<% end %>
</ul>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h2><a href="/">Live</a> | Reports</h2>

<% if !params['debug'] %>
<%= render :partial => "report_ajax", :locals => { :probes => @probes, :days => @number_of_days } %>
<% else %>
<%= render :partial => "report", :locals => { :probes => @probes, :days => @number_of_days } %>
<% end %>

<%= render :partial => 'probes/probes_to_js', :locals => { :probes => @probes } %>
<%= render :partial => 'widgets/widgets_to_js', :locals => { :widgets => ::Widget.sorted } %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @sample.value %>
</p>

<p>
  <b>Date:</b>
  <%= @sample.date %>
</p>

<p>
  <b>Widget:</b>
  <%= @sample.widget_id %>
</p>

<p>
  <b>Status:</b>
  <%= @sample.status %>
</p>

<p>
  <b>Details:</b>
  <%= @sample.details %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>