config/routes.rb
Dashboard::Application.routes.draw do
  resources :notifications

  resources :samples

  resources :probes

  resources :thresholds

  resources :widgets do
    member do 
      get   'process_samples'
    end
    collection do
      post  'sort'
      get   'record_all_samples'
    end
  end

  root :to => 'probes#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  
  has_many    :thresholds, dependent: :destroy
  has_many    :samples, dependent: :destroy
  has_many    :notifications
  belongs_to  :probe
  
  accepts_nested_attributes_for :thresholds, :allow_destroy => true
  
  scope :sorted, Widget.order('position ASC')

  require 'open-uri'
  require 'json'
  require 'socket'  
  
  STATUS = {
    'ok'            => 0,
    'alert'         => 1,
    'warning'       => 2,
    'unresponsive'  => 3,
  }
  
  def Widget.record_all_samples!
    
    for widget in Widget.all
      # record sample asynchronously (delayed job)
      widget.delay.record_sample!
    end
  end

  def record_sample!
    
    logger.debug "fetching #{url}"
    begin
      file = open(url, "x-secret" => Settings.probe_secret)     
      content = JSON.parse(file.read)
      logger.debug "content: #{content.inspect}"
    
      sample = Sample.new({
        :widget_id  => id,
        :value      => content['value'].to_f,
        :status     => service_status_for_value(content['value'].to_f),
        :date       => content['date'],
        :details    => content['details'],
      })
    rescue
      logger.debug "can't access #{url} -> unresponsive"
      sample = Sample.new({
        :widget_id  => id,
        :value      => -1,
        :status     => STATUS['unresponsive'],
        :date       => DateTime.now,
        :details    => {},
      })
    end
    sample.save!
  end
  
  def status
    return -1 if !samples.last
    value = samples.last.value
    service_status_for_value(value)
  end
  
  def service_status_for_value(value)
    
    return STATUS['ok'] if !thresholds
    
    for threshold in thresholds
			if threshold.operator == '>='
				return STATUS[threshold.alert] if value >= threshold.value	
			elsif threshold.operator == '>'
				return STATUS[threshold.alert] if value > threshold.value				
			elsif threshold.operator == '<'
				return STATUS[threshold.alert] if value < threshold.value				
			elsif threshold.operator == '<='
				return STATUS[threshold.alert] if value <= threshold.value				
			elsif threshold.operator == '=='
				return STATUS[threshold.alert] if value == threshold.value				
			elsif threshold.operator == '='
				return STATUS[threshold.alert] if value == threshold.value				
			else
				logger.debug '(service_status_for_value) invalid comparison operator: ' + threshold.operator
      end
    end
    return STATUS['ok']
  end
  
  def has_same_status_several_times?(status, times)
    last_samples = samples.last(times)

    return false if last_samples.size < times

    for sample in last_samples
      return false if sample.status != status
    end
        
    return true    
  end
  
  def Widget.sort! (widget_id_array)
    
    widget_id_array.each_with_index do |widget_id, index|
      widget = Widget.find(widget_id.gsub('widget-',''))
      widget.position = index
      widget.save!
    end
  end
  
  def process_samples(days)
    data = {}
    begin
      data['samples'] = samples.where("created_at > :week", {:week => days.day.ago}).order('date ASC')
      data['average'] = data['samples'].average(:value).round(3)
      data['max']     = data['samples'].maximum(:value)
      data['graph']   = data['samples'].map { |s| s.value }.join(',')
      data['encoded_graph'] = Widget.encode_samples(data['samples'], max)
    rescue
      data['samples'] = []
      data['average'] = -1
      data['max']     = 0
      data['encoded_graph'] = Widget.encode_samples(data['samples'], max)
    end
    return data
  end
  
  def Widget.encode_samples(samples, max_value)
    sample_array = samples.map { |s| s.value } #.join ','
    simpleEncoding = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    chart_data = ['s:']
    if max_value == 0
      max_value = 1
    end
    for sample in sample_array
      if sample < 0 
        chart_data << '_'
      else
        index = ((simpleEncoding.size-1) * sample / max_value)
        if !index.nan?
          chart_data << simpleEncoding[index.round]
        else
          chart_data << '_'          
        end
      end
    end
    return chart_data.join ''
  end
  
  def url
    
    if probe
      #formated_args = args.replace(/&amp;/g, '&')
      if args && args != ''
        "#{probe.url}/#{uri}?#{args}"
      else
        "#{probe.url}/#{uri}"        
      end
    else
      ''
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    @widget = Widget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.json
  def new
    @widget = Widget.new
    @widget.build_data_source()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(params[:widget])
    @widget.id = params[:widget][:id]

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render json: @widget, status: :created, location: @widget }
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.json
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to widgets_path, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end
  
  def sort
    Widget.sort! params[:widget_id_array]
    respond_to do |format|
      format.html { redirect_to widgets_path }
      format.json { head :no_content }
    end
  end
  
  def record_all_samples
    Widget.record_all_samples!
    render nothing: true
  end
  
  def process_samples
    @widget = Widget.find(params[:id])
    @days = params[:days].to_i || 1
    logger.debug "params: #{params}"
    logger.debug "days: #{@days}"
    #data = @widget.process_samples(1)
    data = {}
    data['samples'] = @widget.samples.where("created_at > :days", {:days => @days.day.ago}).order('date ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: data }
    end
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= nested_form_for(@widget) do |f| %>

  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>
      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %> : 
    <%= f.text_field :title %>
  </div>
	
  <div class="field">
    <%= f.label :min %> : <%= f.text_field :min, :size => 10 %>
    <%= f.label :max %> : <%= f.text_field :max, :size => 10 %>
    <%= f.label :unit %> : <%= f.text_field :unit, :size => 4 %>
	  <%= f.label :refresh_delay %> : <%= f.text_field :refresh_delay, :size => 10 %>ms
	</div>
	<!--
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
	-->
	<div class="field">
  	<%= f.label :uri %> : <%= f.text_field :uri, :size => 10 %>
	</div>
	<div class="field">
  	<%= f.label :args %> : <%= f.text_field :args, :size => 60 %>
	</div>

	<div class="field">
  <%= f.label :thresholds %> : 
	<div class="field subform">
	<%= f.fields_for :thresholds do |f_threshold| %>
	<p>
	    <%= render :partial => "thresholds/form", :locals => { :f => f_threshold } %>
	</p>
	<% end %>
	<%= f.link_to_add "Add a threshold", :thresholds %></p>
	</div>
	</div>
  <div class="field">
    <%= f.label :probe %><br />
    <%= f.select :probe_id, ::Probe.all.collect {|p| [ p.title, p.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/_widget_template.html.erb
<script id="widget-empty-template" type="text/x-jquery-tmpl">
<li class="widget service-status-disabled" id="widget-${ widget.id }" >
	<div class="card">
		<div class="face face-simple-view">
			<div class="widget-content">
			</div> <!-- end content -->
		</div> <!-- end face simple view -->
	</div> <!-- end card -->
	<a href="#" class="widget-delete" data-widget-id="${ widget.id }">&#10006;</a>
</li> <!-- end widget -->
</script>

<script id="widget-details" type="text/x-jquery-tmpl">
<div class="tooltip">
	<span class="hours">${ hours }</span>:<span class="minutes">${ minutes }</span>:<span class="seconds">${ seconds }</span>
	<span class="value ${ alert_level }">${ value }</span>${ unit }
	{{if !details==0}}
	<table>
		{{each(name, detail) details}}
			<tr>
				<td><span>${name}</span></td>
				<td><span>${detail}</span></td>
			</tr>
		{{/each}}
	</table>
	{{/if}}
</div>
</script>

<script id="widget-graph" type="text/x-jquery-tmpl">
<li class="widget widget-live service-status-ok" id="widget-${ widget.id }" >
	<div class="card">
		<div class="face face-simple-view">
			<div class="widget-content">
			  <h3>${ widget.title }</h3>
			  <h4 class="status-ok"><span>${ record.value }</span><span class="discreet">${ widget.unit }</span></h4>
			  <div class="plot-chart"></div>
			</div> <!-- end content -->
		</div> <!-- end face simple view -->
	</div> <!-- end card -->
	<a href="#" class="widget-delete" data-widget-id="${ widget.id }">&#10006;</a>
</li> <!-- end widget -->
</script>

<script id="widget-report-graph" type="text/x-jquery-tmpl">
<li class="widget widget-section" id="widget-${ widget.id }">
	<h4>${ widget.title }</h4>
	<h5><span class="value">${ record.value }</span>${ widget.unit }</h5>
	<div class='plot-chart'></div>
</li>
</script>

app/views/widgets/_widgets_to_js.html.erb
<script>
$widgets = {
	
	<% for widget in widgets %>
	'widget-<%= widget.id %>'	: 
	{
		'id'						: '<%= widget.id %>',
		'title' 				: '<%= widget.title %>',
		'args' 					: '<%= widget.args %>',
		<% if widget.uri %>
		'uri'						: '<%= widget.uri %>',
		<% end %>
		'template' 			: '<%= widget.template %>',
		<% if widget.probe %>
		'probe_id' 			: '<%= widget.probe_id %>',
		<% end %>
		<% if widget.thresholds.size > 0 %>
		'thresholds_attributes'	: [
		<% for threshold in widget.thresholds %>
			{ 'operator':'<%= raw threshold.operator %>', 'value': <%= threshold.value %>, 'alert':'<%= threshold.alert %>' },
		<% end %>
		],
		<% end %>
		'min'						: <%= widget.min %>,
		'max'						: <%= widget.max %>,
		'unit'					: '<%= widget.unit %>',
		'refresh_delay'	: <%= widget.refresh_delay %>,
	},
	<% end %>
}
</script>

app/views/widgets/edit.html.erb
<h2>Editing widget</h2>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h2>Dashboard</h2>

<table>
  <tr>
    <th>Widget</th>
    <th>url</th>
    <th>thresholds</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for probe in ::Probe.all %>
<tr><th colspan="4"><%= probe.title %></th></tr>
<% for widget in probe.widgets.sorted %>
  <tr>
    <td><%= widget.title %></td>
    <td><%= widget.uri %></td>
    <td><%= widget.thresholds.size %></td>
    <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
    <td><%= link_to 'Destroy', widget, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>

</table>
<br />


<%= link_to 'New Widget', new_widget_path %> | <%= link_to 'Probes', probes_path %>

app/views/widgets/new.html.erb
<h2>New widget</h2>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<h2><%= @widget.title %></h2>
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @widget.url %>
</p>

<p>
  <b>Data source</b>
	<% if @widget.data_source %>
		<%="#{@widget.data_source.json_url}" %><br />
	<% else %>
	No datasources for this widget.
	<% end %>
</p>


<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>