config/routes.rb
Dashboard::Application.routes.draw do
  resources :notifications

  resources :samples

  resources :probes

  resources :thresholds

  resources :widgets do
    member do 
      get   'process_samples'
    end
    collection do
      post  'sort'
      get   'record_all_samples'
    end
  end

  root :to => 'probes#index'

end

app/models/probe.rb
class Probe < ActiveRecord::Base

  has_many :widgets
  accepts_nested_attributes_for :widgets, :allow_destroy => true
  
  STATUS = {
    'ok'            => 0,
    'alert'         => 1,
    'warning'       => 2,
    'unresponsive'  => 3,
  }
  
  def health
    total_health = 0
    for widget in widgets
      total_health += 1 if widget.status == STATUS['ok'] || widget.status == STATUS['warning']
    end
    (widgets.size>0)?(total_health / widgets.size * 100):100
  end
  
  def Probe.global_health
    global_health = 0
    for probe in Probe.all
      global_health += probe.health
      logger.debug probe.health
    end
    global_health / Probe.all.size
  end
  
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  
  # GET /probes
  # GET /probes.json
  def index
    @number_of_days = params[:days].to_i
    @number_of_days = 1 if @number_of_days == 0
    @probes = Probe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @probes }
    end
  end

  # GET /probes/1
  # GET /probes/1.json
  def show
    @probe = Probe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @probe }
    end
  end

  # GET /probes/new
  # GET /probes/new.json
  def new
    @probe = Probe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @probe }
    end
  end

  # GET /probes/1/edit
  def edit
    @probe = Probe.find(params[:id])
  end

  # POST /probes
  # POST /probes.json
  def create
    @probe = Probe.new(params[:probe])

    respond_to do |format|
      if @probe.save
        format.html { redirect_to probes_path, notice: 'Probe was successfully created.' }
        format.json { render json: @probe, status: :created, location: @probe }
      else
        format.html { render action: "new" }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /probes/1
  # PUT /probes/1.json
  def update
    @probe = Probe.find(params[:id])

    respond_to do |format|
      if @probe.update_attributes(params[:probe])
        format.html { redirect_to '/', notice: 'Probe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @probe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probes/1
  # DELETE /probes/1.json
  def destroy
    @probe = Probe.find(params[:id])
    @probe.destroy

    respond_to do |format|
      format.html { redirect_to probes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/probes/_add_widget_template.html.erb
<script id="add-widget-template" type="text/x-jquery-tmpl">
	<div class="add-widget-form">
		<a href="#" data-dropdown="#probe-${probe_id}-list-modules"  class="button dropdown-button module-dropdown"><b>modules</b><span class="dropdown-caret"> </span></a>
		<a href="#" data-dropdown="#probe-${probe_id}-list-commands" class="button dropdown-button command-dropdown"><b>commands</b><span class="dropdown-caret"> </span></a>
		<input type="text" class="widget-args-input input" value="" size="60"/>
		<a href="#" class="button blue add-widget-button"><b> + add widget</b></a>
	</div>
</script>

<script id="list-probe-modules" type="text/x-jquery-tmpl">
	<div id="probe-${probe_id}-list-modules" class="dropdown dropdown-tip">
		<ul class="dropdown-menu">
		{{each(i, module) modules}}
			<li><a href="#1" data-uri="${module}" class="probe-module">${module}</a></li>
	  {{/each}}
		</ul>
	</div>
</script>

<script id="list-probe-commands" type="text/x-jquery-tmpl">
	<div id="probe-${probe_id}-list-commands" class="dropdown dropdown-tip">
		<ul class="dropdown-menu">
		{{each(i, command) commands}}
			<li>
				<a href="#1" class="probe-command" data-command="${JSON.stringify(command)}" data-module="${module}">
				${command.title} <span class="discreet">(${command.unit})</span>
				</a>
			</li>
	  {{/each}}
		</ul>
	</div>
</script>

app/views/probes/_form.html.erb
<%= nested_form_for(@probe) do |f| %>
  <% if @probe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@probe.errors.count, "error") %> prohibited this probe from being saved:</h2>

      <ul>
      <% @probe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

	<!--
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
	-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/probes/_probe_template.html.erb
<script id="probe-template" type="text/x-jquery-tmpl">
<li class="probe-header" id="probe-${ probe.id }">
	<div class="probe-title-bar">
		<span class="visibility-caret"> </span>
		<span class='probe-title'>${ probe.title }</span>
		<span class='probe-url'>${ probe.url }</span>
		<span class='probe-config'>
			<a href='' class='probe-ok button blue'><b>done</b></a>
			<a href='' class='probe-cancel button discreet'>cancel</a>		
			<a href='' class='probe-add-widget button'><b> + add widget</b></a>
			<a href='' class='probe-edit button'><b>edit</b></a>
		</span>
	</div>
	<ul id="probe-${ probe.id }-widgets" class="widgets">				

	</ul>
</li>
</script>

app/views/probes/_probes_to_js.html.erb
<script>
$probes = {
	<% for probe in probes %>
	'probe-<%= probe.id %>' :
	{
		'id'				: '<%= probe.id %>',
		'title'			: '<%= probe.title %>',
		'url'				: '<%= probe.url %>',		
	},
	<% end %>
}	
</script>

app/views/probes/edit.html.erb
<h2>Editing probe</h2>

<%= render 'form' %>

<%= link_to 'Show', @probe %> |
<%= link_to 'Back', probes_path %>

app/views/probes/index.html.erb
<h2>Live | <a href="/samples">Reports</a></h2>

<ul class="probes" data-days="<%= @number_of_days %>">				

</ul>

<%= render :partial => 'probes/probes_to_js', :locals => {:probes => @probes} %>
<%= render :partial => 'widgets/widgets_to_js', :locals => {:widgets => ::Widget.sorted} %>

<a href="<%= new_probe_path %>" class='button medium'><b> + New Probe</b></a>
<a href="<%= widgets_path %>" class='button medium'><b> Setup widgets</b></a>

app/views/probes/new.html.erb
<h2>New probe</h2>

<%= render 'form' %>

<%= link_to 'Back', probes_path %>

app/views/probes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @probe.title %>
</p>

<p>
  <b>Url:</b>
  <%= @probe.url %>
</p>

<p>
  <b>Position:</b>
  <%= @probe.position %>
</p>


<%= link_to 'Edit', edit_probe_path(@probe) %> |
<%= link_to 'Back', probes_path %>